# .streamlit/secrets.toml
# Reemplace los valores entre comillas con sus claves reales

firebase_key = """
Pega aquí el contenido JSON completo de tu archivo de Firebase (credenciales de servicio)
"""

OWM_KEY = "aquí_va_tu_API_key_de_OpenWeatherMap"

fernet_key = "aquí_va_tu_clave_generada_con_Fernet"
